#!/bin/sh

mkdir -p java-classes

# build into java-classes
javac -cp inst/java/cassandra-driver-core-3.1.3.jar -d java-classes/ java-src/*.java

# set up the jar
(cd java-classes; jar fvc cassandrasimple.jar ./com; mv cassandrasimple.jar ../inst/java)
